apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodies-only-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodies-only
  template:
    metadata:
      labels:
        app: foodies-only
    spec:
      containers:
        - name: foodies-only
          image: dfb5316119e896991a5af7bc36bf4c41a07d6250048b0aec1700500e0cfc159d
          ports:
            - containerPort: 5000
