apiVersion: v1
kind: Service
metadata:
  name: eks-petal-linux-service
  namespace: eks-petal-app
  labels:
    app: eks-petal-linux-app
spec:
  selector:
    app: eks-petal-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80